dad_jokes = {
    1: "Why don't skeletons fight each other? They don't have the guts.",
    2: "What do you call fake spaghetti? An impasta.",
    3: "Why don't some couples go to the gym? Because some relationships don't work out.",
    4: "I would avoid the sushi if I was you. It’s a little fishy.",
    5: "Want to hear a joke about construction? I'm still working on it.",
    6: "What do you call cheese that isn't yours? Nacho cheese.",
    7: "Why couldn’t the bicycle stand up by itself? It was two tired.",
    8: "What did one wall say to the other? I'll meet you at the corner.",
    9: "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
    10: "I used to play piano by ear, but now I use my hands.",
    11: "What do you call an elephant that doesn’t matter? An irrelephant.",
    12: "Why can't you hear a pterodactyl use the bathroom? Because the 'P' is silent.",
    13: "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    14: "Why don’t eggs tell jokes? They’d crack each other up.",
    15: "How does a penguin build its house? Igloos it together.",
    16: "I'm reading a book about anti-gravity. It's impossible to put down!",
    17: "I asked my dog what's two minus two. He said nothing.",
    18: "Why do cows have hooves instead of feet? Because they lactose.",
    19: "I used to hate facial hair, but then it grew on me.",
    20: "What does a zombie vegetarian eat? “GRAAAAAINS!”",
    21: "What's brown and sticky? A stick.",
    22: "Why are elevator jokes so good? They work on so many levels.",
    23: "I only know 25 letters of the alphabet. I don't know y.",
    24: "Did you hear about the circus fire? It was in tents.",
    25: "What do you get when you cross a snowman with a vampire? Frostbite.",
    26: "How do you make a tissue dance? You put a little boogie in it.",
    27: "Why did the math book look sad? Because it had too many problems.",
    28: "Why are fish so smart? Because they live in schools.",
    29: "Did you hear the joke about the roof? Never mind, it's over your head.",
    30: "How does a vampire start a letter? “Tomb it may concern…”",
    31: "I couldn't figure out why the baseball kept getting bigger. Then it hit me.",
    32: "Why did the scarecrow win an award? Because he was outstanding in his field.",
    33: "What did one hat say to the other? Stay here! I'm going on ahead.",
    34: "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
    35: "What’s orange and sounds like a parrot? A carrot.",
    36: "How many apples grow on a tree? All of them.",
    37: "Have you heard about the chocolate record player? It sounds pretty sweet.",
    38: "Why did the chicken go to the seance? To talk to the other side.",
    39: "Why did the coffee file a police report? It got mugged.",
    40: "How does a penguin build its house? Igloos it together.",
    41: "Why don't skeletons fight each other? They don't have the guts.",
    42: "I'm reading a book on anti-gravity. It's impossible to put down.",
    43: "What did the fish say when it hit the wall? Dam.",
    44: "How does a snowman get around? By riding an 'icicle'.",
    45: "Why don’t oysters donate to charity? Because they are shellfish.",
    46: "How do you make a lemon drop? Just let it fall.",
    47: "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    48: "What does a bee use to brush its hair? A honeycomb.",
    49: "I would tell you a joke about an elevator, but it's an uplifting experience.",
    50: "Why don’t skeletons fight? They don’t have the guts.",
    51: "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    52: "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    53: "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    54: "Want to hear a joke about paper? Never mind, it’s tearable.",
    55: "Why was the math book sad? It had too many problems.",
    56: "How do you organize a space party? You planet.",
    57: "What do you call an alligator in a vest? An investigator.",
    58: "What’s a skeleton’s least favorite room in the house? The living room.",
    59: "Why did the cookie go to the hospital? Because it felt crummy.",
    60: "I used to play piano by ear, but now I use my hands.",
    61: "How does a train eat? It goes chew chew.",
    62: "What’s the most musical part of the chicken? The drumstick.",
    63: "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    64: "What do you call a fake noodle? An impasta.",
    65: "How do cows stay up to date? They read the moos-paper.",
    66: "Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field.",
    67: "I would tell you a joke about an elevator, but it's an uplifting experience.",
    68: "Why did the coffee file a police report? It got mugged.",
    69: "Why can't you hear a pterodactyl in the bathroom? Because the 'P' is silent.",
    70: "Why do elephants paint their toenails red? So they can hide in cherry trees.",
    71: "What do you call an alligator in a vest? An investigator.",
    72: "I’ve just written a song about a tortilla. Well, it’s more of a wrap.",
    73: "What do you call a dog magician? A labracadabrador.",
    74: "How do you organize a space party? You planet.",
    75: "What’s Forrest Gump’s password? 1forrest1.",
    76: "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    77: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    78: "What do you get when you cross a snowman with a vampire? Frostbite.",
    79: "Why was the math book sad? It had too many problems.",
    80: "How do you make a lemon drop? Just let it fall.",
    81: "What do you call cheese that isn't yours? Nacho cheese.",
    82: "How do cows stay up to date? They read the moos-paper.",
    83: "Why was the baby strawberry crying? Because its parents were in a jam.",
    84: "What does a snowman eat for breakfast? Frosted flakes.",
    85: "How does the moon cut his hair? Eclipse it.",
    86: "What’s orange and sounds like a parrot? A carrot.",
    87: "Why did the coffee file a police report? It got mugged.",
    88: "What do you call a fake noodle? An impasta.",
    89: "Why are elevator jokes so good? They work on so many levels.",
    90: "What do you call a cow with no legs? Ground beef.",
    91: "Why do cows wear bells? Because their horns don’t work.",
    92: "Why don’t skeletons fight each other? They don’t have the guts.",
    93: "What did the janitor say when he jumped out of the closet? Supplies!",
    94: "What did one hat say to the other? Stay here, I'm going on ahead.",
    95: "Why don't scientists trust atoms? Because they make up everything.",
    96: "How do you catch a squirrel? Climb into a tree and act like a nut.",
    97: "Why did the invisible man turn down the job offer? He couldn’t see himself doing it.",
    98: "How does a train eat? It goes chew chew.",
    99: "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    100: "What did the buffalo say to his son when he dropped him off at school? Bison.",
    101: "Why don't eggs tell jokes? Because they'd crack up.",
    102: "Why are skeletons so calm? Because nothing gets under their skin.",
    103: "I’m on a seafood diet. I see food and I eat it.",
    104: "Why did the tomato turn red? Because it saw the salad dressing.",
    105: "Why do cows have hooves instead of feet? Because they lactose.",
    106: "What does a vampire call a blood donation? A gravy train.",
    107: "How many tickles does it take to make an octopus laugh? Ten-tickles.",
    108: "How do you make holy water? You boil the hell out of it.",
    109: "How does a penguin build its house? Igloos it together.",
    110: "What do you call a deer with no eyes? No eye-deer.",
    111: "What do you call a man with no arms and no legs in a pool? Bob.",
    112: "Why did the banana go to the doctor? Because it wasn’t peeling well.",
    113: "What did the pirate say on his 80th birthday? Aye matey.",
    114: "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
    115: "Why do fish live in salt water? Because pepper makes them sneeze.",
    116: "What do you call a cow with no legs? Ground beef.",
    117: "What does a bee use to brush its hair? A honeycomb.",
    118: "What do you call a snowman with a six-pack? An abdominal snowman.",
    119: "Why did the chicken go to the seance? To talk to the other side.",
    120: "Why don’t elephants use computers? Because they’re afraid of the mouse.",
    121: "How does the ocean say hi? It waves.",
    122: "What did one plate say to the other? Lunch is on me.",
    123: "What do you call a fish that wears a crown? A kingfish.",
    124: "What’s brown and sticky? A stick.",
    125: "What did the grape do when it got stepped on? Nothing, it just let out a little wine.",
    126: "Why did the scarecrow win an award? Because he was outstanding in his field.",
    127: "How does a vampire start a letter? Tomb it may concern...",
    128: "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    129: "What did one hat say to the other? You stay here, I’ll go on ahead.",
    130: "What does a zombie vegetarian eat? “GRAAAAAINS!”",
    131: "How do you make a tissue dance? Put a little boogie in it.",
    132: "What do you call a bear with no teeth? A gummy bear.",
    133: "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    134: "What’s black, white, and red all over? A sunburnt zebra.",
    135: "What did the janitor say when he jumped out of the closet? Supplies!",
    136: "What do you call a snowman with a six-pack? An abdominal snowman.",
    137: "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    138: "What did one wall say to the other? I'll meet you at the corner.",
    139: "Why are spiders so smart? They can find everything on the web.",
    140: "What do you get when you cross a snowman with a vampire? Frostbite.",
    141: "Why don't you ever hear a pterodactyl go to the bathroom? Because the 'P' is silent.",
    142: "Why was Cinderella so bad at soccer? Because she kept running away from the ball.",
    143: "Why don't ants get sick? Because they have tiny ant-bodies.",
    144: "Why was the tomato blushing? Because it saw the salad dressing.",
    145: "Why don’t sharks play cards? Because they’re afraid of the deck.",
    146: "What’s green and has wheels? Grass, I lied about the wheels.",
    147: "What’s brown and sounds like a bell? Dung!",
    148: "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    149: "I used to hate facial hair, but then it grew on me.",
    150: "What’s blue and smells like red paint? Blue paint."
}